### ISSUE TITLE
Can I get to know how the name 'mustang' came into your mind?

### ISSUE THREAD

**Issue by sudipghimire533** [sunfishcode/mustang#1]
Title says it all

**Comment by sunfishcode** [comment]
A [mustang](http://dict.org/bin/Dict?Form=Dict2&Database=*&Query=mustang) is like a [`steed`](https://github.com/japaric/steed), but a little wilder. Or something like that :smile:

**Comment by sudipghimire533** [comment]
Ae. There's a really nice place in my country Nepal with name "Mustang" and I couldn't stop the urge to wonder If that was where you derived this name from.

**Comment by sunfishcode** [comment]
Ah, unfortunately it was not. But perhaps some day this `mustang` crate can aspire to grow beyond its rather wild present state into such a nice place as Mustang.
