### ISSUE TITLE
Why are mustang targets named *-mustang-*-*?

### ISSUE THREAD

**Issue by Gaelan** [sunfishcode/mustang#111]
Currently, Mustang's targets are named `*-mustang-linux-gnu`. This seems a little odd—usually, the last field of the target "triple" indicates the libc used (e.g. `x86_64-unknown-linux-gnu` vs `x86_64-unknown-linux-musl`). Given that Mustang is something like a libc replacement, wouldn't `x86_64-unknown-linux-mustang` make more sense?

Sorry if I'm missing something obvious!

**Comment by bjorn3** [comment]
I believe it intends to be abi compatible with glibc and as such should have a target_env of gnu.

**Comment by Gaelan** [comment]
Ah, right, that makes enough sense.
