### ISSUE TITLE
Consider `nodefaultlibs` linker args instead of empty object files

### ISSUE THREAD

**Issue by carbotaniuman** [sunfishcode/mustang#129]
I see a bunch of empty object files in the `mustang` folder, and was wondering if `nodefaultlibs` was tested to avoid the linker linking them in, or if that had any issues. It seems like a much cleaner way of doing things.

**Comment by sunfishcode** [comment]
I agree, and it's what I originally tried to do, but it turns out that the Rust driver adds its own `-lc` and friends, even when `-nostdlib` is added to the linker arguments.

**Comment by sunfishcode** [comment]
Closing as answered, though I'm open to further discussion if anyone has any ideas for how to do this.
