### ISSUE TITLE
Mustang doesn't build on Right nightly >= 2023-05-26

### ISSUE THREAD

**Issue by sunfishcode** [sunfishcode/mustang#216]
Mustang builds on Rust nightly 2023-05-25 but not 2023-05-26. Building the `hello` example, for example, gets these errors:
<details>
   Compiling mustang-examples v0.8.13 (/code/hub/ecosystem/mustang)
error: linking with `cc` failed: exit status: 1
  |
  = note: LC_ALL="C" PATH="/code/.rustup/toolchains/nightly-2023-05-26-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin:/code/.volta/bin:/code/.cargo/bin:/code/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin" VSLANG="1033" "cc" "-m64" "-nostartfiles" "-Wl,--undefined=_Unwind_Backtrace" "/tmp/rustcwD5K7D/symbols.o" "/code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/examples/hello-88c00dfb9410b272.1e6qua1pimn9r3dc.rcgu.o" "/code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/examples/hello-88c00dfb9410b272.20c0ixtw6q6pssol.rcgu.o" "/code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/examples/hello-88c00dfb9410b272.230g05hk0ixxwp7y.rcgu.o" "/code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/examples/hello-88c00dfb9410b272.2p77a6fwdwb020vy.rcgu.o" "/code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/examples/hello-88c00dfb9410b272.2y7a9nlrvn4mbggz.rcgu.o" "/code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/examples/hello-88c00dfb9410b272.3klzgo2iwludrkvi.rcgu.o" "/code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/examples/hello-88c00dfb9410b272.4d7ou71os8xjnxe0.rcgu.o" "/code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/examples/hello-88c00dfb9410b272.sf2b0l4p0h7kfqy.rcgu.o" "-Wl,--as-needed" "-L" "/code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps" "-L" "/code/hub/ecosystem/mustang/target/debug/deps" "-L" "/code/hub/ecosystem/mustang/mustang/empty/x86_64" "-L" "/code/hub/ecosystem/mustang/mustang/empty/x86_64" "-L" "/code/hub/ecosystem/mustang/mustang/empty/x86_64" "-L" "/code/hub/ecosystem/mustang/mustang/empty/x86_64" "-L" "/code/hub/ecosystem/mustang/mustang/empty/x86_64" "-L" "/code/hub/ecosystem/mustang/mustang/empty/x86_64" "-L" "/code/hub/ecosystem/mustang/mustang/empty/x86_64" "-L" "/code/hub/ecosystem/mustang/mustang/empty/x86_64" "-L" "/code/hub/ecosystem/mustang/mustang/empty/x86_64" "-L" "/code/hub/ecosystem/mustang/mustang/empty/x86_64" "-L" "/code/hub/ecosystem/mustang/mustang/empty/x86_64" "-L" "/code/hub/ecosystem/mustang/mustang/empty/x86_64" "-L" "/code/.rustup/toolchains/nightly-2023-05-26-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-mustang-linux-gnu/lib" "-Wl,-Bstatic" "/code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/libmustang-a3af5fc6e79367f8.rlib" "/code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/libdlmalloc-7bce3d77822cee7f.rlib" "/code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/libunwinding-60a9f5050f9e581d.rlib" "/code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/libgimli-04af3a7b585af884.rlib" "/code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/libc_gull-b4f6dcd13bef314a.rlib" "/code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/libtz-69fcd02301332cfb.rlib" "/code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/libsync_resolve-00502edfb7dc7820.rlib" "/code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/liblog-7db59f95cc5d9b27.rlib" "/code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/libidna-96f0ada89607504f.rlib" "/code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/libunicode_normalization-0e19a69583170111.rlib" "/code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/libtinyvec-8106fef157bc1e70.rlib" "/code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/libtinyvec_macros-12b8a26502bca248.rlib" "/code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/libunicode_bidi-d227bd52e2e0d9a3.rlib" "/code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/libmatches-4293729cb96e416f.rlib" "/code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/libprintf_compat-07bc30abe31393ad.rlib" "/code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/libitertools-335421605044b6fa.rlib" "/code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/libeither-cbbf08509d15782e.rlib" "/code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/libcstr_core-38048e5c767af929.rlib" "/code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/libmemchr-b47f1b4b82c2f1ad.rlib" "/code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/libcty-5d9ee19b2757ddfe.rlib" "/code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/libc_scape-9f478051aa7c8dd1.rlib" "/code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/liblibm-cc4960d5e087457c.rlib" "/code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/librealpath_ext-c62f0be5f2a9acf4.rlib" "/code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/librand_pcg-5b929eb0b983022c.rlib" "/code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/librand-7c262fcb01c6589a.rlib" "/code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/librand_chacha-ebd5a68a65538dcd.rlib" "/code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/libppv_lite86-4ad5be6cdc9c8128.rlib" "/code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/librand_core-436ac72b34c3094c.rlib" "/code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/libgetrandom-dd56703bdd216e27.rlib" "/code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/libcfg_if-38db8dae6b99afdd.rlib" "/code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/liberrno-3394e6391bd1ab67.rlib" "/code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/liborigin-9b38cf2503373924.rlib" "/code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/libmemoffset-4fb93e6a620d9a43.rlib" "/code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/librustix-bbf3a6105699e5da.rlib" "/code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/libitoa-34aac50717761f34.rlib" "/code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/libonce_cell-995979501fa3740f.rlib" "/code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/libio_lifetimes-6686dd988396f23e.rlib" "/code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/libbitflags-2f382964a6069837.rlib" "/code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/liblinux_raw_sys-db73f961bf02de52.rlib" "/code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/liblock_api-1737e08fe19a0fb1.rlib" "/code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/libscopeguard-69668745e5b29c02.rlib" "/code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/liblibc-0567ac215b63b73a.rlib" "/code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/libstd-02f8a7b7a1901642.rlib" "/code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/libpanic_unwind-07524f9bfb05ebac.rlib" "/code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/libobject-0ce2f1a0b296314f.rlib" "/code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/libmemchr-484179612f137c4b.rlib" "/code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/libaddr2line-5d60b74f46aa6051.rlib" "/code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/libgimli-a2447cf2bcffaebd.rlib" "/code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/librustc_demangle-26a312dfbc0220d1.rlib" "/code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/libstd_detect-f7f8718d9efcd7eb.rlib" "/code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/libhashbrown-594fbfdacd6c30c3.rlib" "/code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/librustc_std_workspace_alloc-b4e6cd0d321d5ba1.rlib" "/code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/libminiz_oxide-39eb2afc954ba3f1.rlib" "/code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/libadler-eb4942e3e54eb41f.rlib" "/code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/libunwind-805f5c36ab59e386.rlib" "/code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/libcfg_if-4b717b91b60ce4a9.rlib" "/code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/liblibc-6fa8e3ef49ed4b20.rlib" "/code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/liballoc-471073f9e0e91284.rlib" "/code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/librustc_std_workspace_core-1b16d74b84640c84.rlib" "/code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/libcore-f2164af8f7291745.rlib" "/code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/libcompiler_builtins-7c808cc6daf28e1d.rlib" "-Wl,-Bdynamic" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-z,noexecstack" "-L" "/code/.rustup/toolchains/nightly-2023-05-26-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-mustang-linux-gnu/lib" "-o" "/code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/examples/hello-88c00dfb9410b272" "-Wl,--gc-sections" "-pie" "-Wl,-z,relro,-z,now" "-nodefaultlibs"
  = note: /usr/bin/ld: /code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/libc_scape-9f478051aa7c8dd1.rlib(c_scape-9f478051aa7c8dd1.47camd0fdacd5v7r.rcgu.o): in function `alloc::alloc::alloc_zeroed':
          /code/.rustup/toolchains/nightly-2023-05-26-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/alloc.rs:174: undefined reference to `__rust_alloc_zeroed'
          /usr/bin/ld: /code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/libc_scape-9f478051aa7c8dd1.rlib(c_scape-9f478051aa7c8dd1.47camd0fdacd5v7r.rcgu.o): in function `alloc::alloc::alloc':
          /code/.rustup/toolchains/nightly-2023-05-26-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/alloc.rs:102: undefined reference to `__rust_alloc'
          /usr/bin/ld: /code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/libc_scape-9f478051aa7c8dd1.rlib(c_scape-9f478051aa7c8dd1.47camd0fdacd5v7r.rcgu.o): in function `alloc::alloc::dealloc':
          /code/.rustup/toolchains/nightly-2023-05-26-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/alloc.rs:121: undefined reference to `__rust_dealloc'
          /usr/bin/ld: /code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/liborigin-9b38cf2503373924.rlib(origin-9b38cf2503373924.48kshjsqrbld9jcc.rcgu.o): in function `alloc::alloc::dealloc':
          /code/.rustup/toolchains/nightly-2023-05-26-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/alloc.rs:121: undefined reference to `__rust_dealloc'
          /usr/bin/ld: /code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/librustix-bbf3a6105699e5da.rlib(rustix-bbf3a6105699e5da.rustix.2459406bb3336314-cgu.15.rcgu.o): in function `alloc::alloc::alloc_zeroed':
          /code/.rustup/toolchains/nightly-2023-05-26-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/alloc.rs:174: undefined reference to `__rust_alloc_zeroed'
          /usr/bin/ld: /code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/librustix-bbf3a6105699e5da.rlib(rustix-bbf3a6105699e5da.rustix.2459406bb3336314-cgu.15.rcgu.o): in function `alloc::alloc::alloc':
          /code/.rustup/toolchains/nightly-2023-05-26-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/alloc.rs:102: undefined reference to `__rust_alloc'
          /usr/bin/ld: /code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/libstd-02f8a7b7a1901642.rlib(std-02f8a7b7a1901642.std.4a0524abeebcbf7e-cgu.4.rcgu.o): in function `alloc::alloc::alloc_zeroed':
          /code/.rustup/toolchains/nightly-2023-05-26-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/alloc.rs:174: undefined reference to `__rust_alloc_zeroed'
          /usr/bin/ld: /code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/libstd-02f8a7b7a1901642.rlib(std-02f8a7b7a1901642.std.4a0524abeebcbf7e-cgu.4.rcgu.o): in function `alloc::alloc::alloc':
          /code/.rustup/toolchains/nightly-2023-05-26-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/alloc.rs:102: undefined reference to `__rust_alloc'
          /usr/bin/ld: /code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/libstd-02f8a7b7a1901642.rlib(std-02f8a7b7a1901642.std.4a0524abeebcbf7e-cgu.4.rcgu.o): in function `alloc::alloc::dealloc':
          /code/.rustup/toolchains/nightly-2023-05-26-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/alloc.rs:121: undefined reference to `__rust_dealloc'
          /usr/bin/ld: /code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/libstd-02f8a7b7a1901642.rlib(std-02f8a7b7a1901642.std.4a0524abeebcbf7e-cgu.4.rcgu.o): in function `alloc::alloc::realloc':
          /code/.rustup/toolchains/nightly-2023-05-26-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/alloc.rs:140: undefined reference to `__rust_realloc'
          /usr/bin/ld: /code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/libpanic_unwind-07524f9bfb05ebac.rlib(panic_unwind-07524f9bfb05ebac.panic_unwind.9f5d49f6e7999dfe-cgu.11.rcgu.o): in function `alloc::alloc::alloc_zeroed':
          /code/.rustup/toolchains/nightly-2023-05-26-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/alloc.rs:174: undefined reference to `__rust_alloc_zeroed'
          /usr/bin/ld: /code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/libpanic_unwind-07524f9bfb05ebac.rlib(panic_unwind-07524f9bfb05ebac.panic_unwind.9f5d49f6e7999dfe-cgu.11.rcgu.o): in function `alloc::alloc::alloc':
          /code/.rustup/toolchains/nightly-2023-05-26-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/alloc.rs:102: undefined reference to `__rust_alloc'
          /usr/bin/ld: /code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/libpanic_unwind-07524f9bfb05ebac.rlib(panic_unwind-07524f9bfb05ebac.panic_unwind.9f5d49f6e7999dfe-cgu.11.rcgu.o): in function `alloc::alloc::dealloc':
          /code/.rustup/toolchains/nightly-2023-05-26-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/alloc.rs:121: undefined reference to `__rust_dealloc'
          /usr/bin/ld: /code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/libgimli-a2447cf2bcffaebd.rlib(gimli-a2447cf2bcffaebd.gimli.b97ed1a92c3f8633-cgu.15.rcgu.o): in function `alloc::alloc::alloc_zeroed':
          /code/.rustup/toolchains/nightly-2023-05-26-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/alloc.rs:174: undefined reference to `__rust_alloc_zeroed'
          /usr/bin/ld: /code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/libgimli-a2447cf2bcffaebd.rlib(gimli-a2447cf2bcffaebd.gimli.b97ed1a92c3f8633-cgu.15.rcgu.o): in function `alloc::alloc::alloc':
          /code/.rustup/toolchains/nightly-2023-05-26-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/alloc.rs:102: undefined reference to `__rust_alloc'
          /usr/bin/ld: /code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/libgimli-a2447cf2bcffaebd.rlib(gimli-a2447cf2bcffaebd.gimli.b97ed1a92c3f8633-cgu.15.rcgu.o): in function `alloc::alloc::dealloc':
          /code/.rustup/toolchains/nightly-2023-05-26-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/alloc.rs:121: undefined reference to `__rust_dealloc'
          /usr/bin/ld: /code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/liballoc-471073f9e0e91284.rlib(alloc-471073f9e0e91284.alloc.b507f0f71a72fbe9-cgu.5.rcgu.o): in function `alloc::alloc::alloc':
          /code/.rustup/toolchains/nightly-2023-05-26-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/alloc.rs:102: undefined reference to `__rust_alloc'
          /usr/bin/ld: /code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/liballoc-471073f9e0e91284.rlib(alloc-471073f9e0e91284.alloc.b507f0f71a72fbe9-cgu.5.rcgu.o): in function `alloc::alloc::dealloc':
          /code/.rustup/toolchains/nightly-2023-05-26-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/alloc.rs:121: undefined reference to `__rust_dealloc'
          /usr/bin/ld: /code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/liballoc-471073f9e0e91284.rlib(alloc-471073f9e0e91284.alloc.b507f0f71a72fbe9-cgu.5.rcgu.o): in function `alloc::alloc::realloc':
          /code/.rustup/toolchains/nightly-2023-05-26-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/alloc.rs:140: undefined reference to `__rust_realloc'
          /usr/bin/ld: /code/hub/ecosystem/mustang/target/x86_64-mustang-linux-gnu/debug/deps/liballoc-471073f9e0e91284.rlib(alloc-471073f9e0e91284.alloc.b507f0f71a72fbe9-cgu.5.rcgu.o): in function `alloc::alloc::alloc_zeroed':
          /code/.rustup/toolchains/nightly-2023-05-26-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/alloc.rs:174: undefined reference to `__rust_alloc_zeroed'
          collect2: error: ld returned 1 exit status

  = note: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname)

error: could not compile `mustang-examples` (example "hello") due to previous error
</details>

**Comment by bjorn3** [comment]
This is likely https://github.com/rust-lang/rust/issues/112715 which wil be fixed by https://github.com/rust-lang/rust/pull/112794.

**Comment by sunfishcode** [comment]
Awesome, thanks!

**Comment by sunfishcode** [comment]
This is now fixed, and with #215 mustang is now using an updated nightly.
