### ISSUE TITLE
Investigate other allocators

### ISSUE THREAD

**Issue by sunfishcode** [sunfishcode/mustang#28]
`wee_alloc` works great, but is designed for small code size rather than efficiency, and has `O(n)` allocation, and by its own description is "geared towards code that makes a handful of initial dynamically sized allocations, and then performs its heavy lifting without any further allocations", so it'd be nice to have other options.

A brief search turned up a few possible alternatives:
 - [elfmalloc](https://github.com/ezrosent/allocators-rs/tree/master/elfmalloc)
 - [ralloc](https://github.com/redox-os/ralloc)

Unfortunately, neither of these seems to have seen any updates in years, and it seems neither works with `#[global_allocator]` out of the box, so some work is likely needed.

**Comment by bjorn3** [comment]
Libstd uses the [dlmalloc](https://docs.rs/dlmalloc/0.2.1/dlmalloc/) crate by default for wasm. It is a port of the C allocator with the same name. I believe it has decent performance.

https://web.archive.org/web/20190619034641/http://g.oswego.edu/dl/html/malloc.html

Wasi-libc also uses the C version of dlmalloc: https://github.com/WebAssembly/wasi-libc/blob/ad5133410f66b93a2381db5b542aad5e0964db96/Makefile#L14

**Comment by sunfishcode** [comment]
Thanks! I had missed that `dlmalloc` is actually written in Rust, rather than being Rust bindings for the C `dlmalloc`.
