### ISSUE TITLE
Please document the intended policy for minimum Linux kernel versions

### ISSUE THREAD

**Issue by joshtriplett** [sunfishcode/mustang#47]
I'd love to see mustang have a documented policy for how it selects the minimum Linux kernel version it supports, as well as the current minimum version.

I can imagine three possible policies here:

1. Recent kernels: require a relatively recent kernel, so that mustang can unconditionally use new system calls without fallbacks (or missing functionality if there's no reasonable fallback). This would be appropriate if mustang is primarily demonstrating the best and simplest possible implementation path, without worrying about widespread production use outside of deployment environments people can entirely control.
2. Stable kernels: Require a kernel within the last few years, roughly allowing for "last stable release of common Linux distributions". This would require some fallbacks for new functionality, but fewer of them. This would be appropriate for widespread production use of mustang, including use in containers and distribution of common tools (e.g. precompiled versions of command-line tools).
3. Enterprise kernels: Support every kernel version Rust currently supports. This would require the largest number of fallbacks, but support anyone who could possibly run mustang on any Rust system.

**Comment by sunfishcode** [comment]
Here's how things look to me right now.

std tends to avoid features which don't work on all supported Linux versions. And std already does use new Linux syscalls to optimize things when they happen to fit into what it's already doing. As such, there aren't many opportunities to use new Linux syscalls to do the things std does in different ways. It'd be fun to avoid `ENOSYS`/`AtomicBool` code dealing with older versions, and it'd be fun to have a codebase with fewer `#[cfg(...)]`s, but those aren't clearly worth all the work they would require.

If someone sees an opportunity to do things differently, or wants to help out with the work required to do something different, I'm open to it. But until then, it seems like Mustang will continue to pursue something like option 3: Aim to support all versions of Linux supported by Rust. We don't have testing for the older versions yet, so there could be bugs yet, but hopefully we'll fix those over time.

**Comment by sunfishcode** [comment]
I've now posted https://github.com/sunfishcode/mustang/pull/74 to document this.

**Comment by sunfishcode** [comment]
The policy is now documented. As I mentioned above, I'm happy to discuss opportunities to do something different.
