### ISSUE TITLE
Optimize `memchr` etc.

### ISSUE THREAD

**Issue by sunfishcode** [sunfishcode/mustang#5]
Currently c-scape's implementation of `memchr` and similar functions is [very simple](https://github.com/sunfishcode/mustang/blob/43714a0c90bb85535a6500b52397d8b1aa858f89/c-scape/src/c.rs#L225). It may be possible to optimize them using the [memx crate](https://crates.io/crates/memx).

c-scape is compiled with `#![no_builtins`] to discourage the compiler from optimizing the definitions of C library functions into calls to C library functions, however the compiler can still generate calls to `memcpy`, `memmove`, `memset`, and `memcmpy`, so we need to be careful the compiler doesn't do that with the implementations of those functions :-).

**Comment by bjorn3** [comment]
Would it be possible to directly use compiler-builtins? It gets published on crates.io and should also be part of the sysroot.

**Comment by sunfishcode** [comment]
Cool, I didn't know compiler-builtins had `memcpy` etc., that looks like a good idea.

**Comment by sunfishcode** [comment]
And another resource here is the [`memchr` crate](https://docs.rs/memchr/2.4.1/memchr/).

If anyone's interested in working on this, the first step would be to use the `mem*` functions in [compiler_builtins](https://docs.rs/compiler_builtins/0.1.50/compiler_builtins/mem/index.html#functions) to implement the corresponding `mem*` functions in mustang.

**Comment by cole-miller** [comment]
I'm interested in working on this!

**Comment by sunfishcode** [comment]
Thanks! If you're interested, I think the next step would be `memchr` and `memrchr` using either the `memchr` or `memx` crates.

**Comment by sunfishcode** [comment]
With #9 and #10 merged, this is now implemented!
