### ISSUE TITLE
Implement inotify

### ISSUE THREAD

**Issue by sunfishcode** [sunfishcode/mustang#85]
As reported [here](https://github.com/sunfishcode/mustang/issues/22#issuecomment-988534324), this is needed for cargo-watch.

**Comment by passcod** [comment]
Hi, I'm the maintainer of cargo watch! I'd be really interested in supporting this. Is there a guide to implementing these calls?

**Comment by Urgau** [comment]
The first thing would be to implement an API for them in [rustix](https://github.com/bytecodealliance/rustix) (the underline rust wrapper for kernel and some posix APIs) based on their c implementations ([musl](https://github.com/BlankOn/musl/blob/master/src/linux/inotify.c) or [glibc](https://github.com/bminor/glibc/blob/30891f35fa7da832b66d80d0807610df361851f3/sysdeps/unix/sysv/linux/generic/inotify_init.c)). Then add to the `c-scape` crate the c APIs for these based on the newly added API in rustix. That should be all but sunfishcode should confirm.

**Comment by sunfishcode** [comment]
Confirmed :-). For the rustix API, I suggest modelling it after the [inotify-sys API](https://docs.rs/inotify-sys/latest/inotify_sys/), except with rustix's conventions: `OwnedFd`/`AsFd` instead of `c_int` for file descriptors, `Result`s instead of `-1`s and `errno`, `bitflags` for flags, `rustix::path::Arg` instead of `*const c_char`, and so on. The `eventfd` API in rustix might be useful to look at to get a sense of what an API like this looks like in rustix. I'd be happy to walk through the process in more detail if that would help, or answer any questions that come up.

Once the rustix API is in place, adding a C API to c-scape crate is indeed one option. As above, `eventfd` might be a useful starting point here.

There is also another option, in case there's interest: port the inotify crate to use this new rustix inotify API, instead of inotify-sys and libc. In theory this should be straightforward, and should significantly simplify the inotify crate's code, for example by replacing all the code that does versions of `if res == -1 { return Err(io::Error::last_os_error()); }` with just `?`, and factoring out most of the `unsafe` blocks.

**Comment by sunfishcode** [comment]
With https://github.com/bytecodealliance/rustix/issues/538, rustix now has an [inotify API](https://docs.rs/rustix/latest/rustix/fs/inotify/index.html).

**Comment by sunfishcode** [comment]
This is needed by uutils/coreutils' `tail` command.
