### ISSUE TITLE
Implement `pipe`

### ISSUE THREAD

**Issue by sunfishcode** [sunfishcode/mustang#88]
As reported [here](https://github.com/sunfishcode/mustang/issues/22#issuecomment-988534324), this is needed for cargo-watch.

c-scape already has `pipe2` implemented, so `pipe` should be the same but without flags.

**Comment by BenStruhl** [comment]
I can take this : )

**Comment by sunfishcode** [comment]
Great! Please feel free to ask questions if anything is unclear!

**Comment by BenStruhl** [comment]
hmm are you on the official discord server too? should I implement it in rustix first?

**Comment by sunfishcode** [comment]
Normally, yes, the first step would be to add it to rustix. In this case, it turns out [rustix already has it](https://docs.rs/rustix/latest/rustix/io/fn.pipe.html). The next step is to add it to c-scape, following `pipe2` as an example.

**Comment by carbotaniuman** [comment]
Being implemented in #104.

**Comment by sunfishcode** [comment]
This is implemented in #104.
