### ISSUE TITLE
c-scape's `same_ptr*` functions dont check layout equality

### ISSUE THREAD

**Issue by nivkner** [sunfishcode/mustang#90]
the functions use the runtime check `assert_eq!(core::mem::size_of::<T>(), core::mem::size_of::<U>());`,
inside a branch that is never evaluated, because of the `false` condition in the `libc!`.
so even when the layout of the pointee types mismatch, the CI still passes.

**Comment by sunfishcode** [comment]
Wow, good catch! That's definitely not intended.
